"""removed column

Revision ID: 29b6436597d7
Revises: 739bbae8b6cd
Create Date: 2025-03-06 18:07:42.618693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '29b6436597d7'
down_revision: Union[str, None] = '739bbae8b6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
